spring:
  application:
   name: agent-ai
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:7b
    openai:
      api-key: sk-6
logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.tmd.ai: debug