spring:
  application:
   name: agent-ai
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:8b
    openai:
      api-key: sk-6ba44564c1ab4c80b1e012a7fb89dd87
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen-max-latest
logging:
  level:
    org.springframework.ai: debug
    com.tmd.ai: debug